### ISSUE TITLE
Flesh out About page

### ISSUE THREAD

**Issue by SuperShadowPlay** [codi-hacks/weather-station#49]
The About page on the web app is currently one line of text. Make it not so!
A few starter ideas on what to include:
- State the purpose of this project.
- Explain the features.
- Possibly give a brief overview of the frameworks and languages that make the project possible (Vue, Rust, the weather station hardware, etc.)

**Comment by jaythomas** [comment]
Also move the "Source Code" link out of the top bar and over to the About page would be good.
